export const SET = 'SET';
export const SET_ARRAY = 'SET_ARRAY';

export const PUSH_ARRAY = 'PUSH_ARRAY';

export const SET_FOCUSED = 'SET_FOCUSED';
export const SET_BLURRED = 'SET_BLURRED';

export const CHANGE_TRAIN = 'CHANGE_TRAIN';
export const CHANGE_DEVICE = 'CHANGE_DEVICE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_SECTION_TYPE = 'CHANGE_SECTION_TYPE';
export const CHANGE_SECTION_TIME = 'CHANGE_SECTION_TIME';
export const CHANGE_SECTION_DISTANCE = 'CHANGE_SECTION_DISTANCE';
export const CHANGE_PARAMETER_FILTERING = 'CHANGE_PARAMETER_FILTERING';


export const TOGGLE_MAP_RAILWAY = 'TOGGLE_MAP_RAILWAY';
export const TOGGLE_MAP_CITY_BORDER = 'TOGGLE_MAP_CITY_BORDER';
export const TOGGLE_MAP_CITY_NAME = 'TOGGLE_MAP_CITY_NAME';


export const CHANGE_DURATION = 'CHANGE_DURATION';
export const CHANGE_TIMING = 'CHANGE_TIMING';
export const CHANGE_CALENDAR_RANGE = 'CHANGE_CALENDAR_RANGE';

export const CHANGE_SORTING = 'CHANGE_SORTING';

export const CHANGE_OPEN_TOOL = 'CHANGE_OPEN_TOOL';
export const CLOSE_OPEN_TOOL = 'CLOSE_OPEN_TOOL';


export const SELECT_SIGNAL = 'SELECT_SIGNAL';
export const SELECT_ALL = 'SELECT_ALL';

export const ADD_DOWNLOAD_QUEUE = 'ADD_DOWNLOAD_QUEUE';
export const DOWNLOAD_COMPLETED = 'DOWNLOAD_COMPLETED';

export const CHANGE_MAP_POINTS = 'CHANGE_MAP_POINTS';


export const REQUEST_VIDEO = 'REQUEST_VIDEO';

export const SIGNAL_DETAIL = 'SIGNAL_DETAIL';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
